// src/app/component/register/register.component.ts
import { Component } from '@angular/core';
import { AppComponent } from 'src/app/app.component';
import { disableForms } from 'src/app/method';
import { Api } from 'src/coral-api/api';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  register(){
    
    const loginR_ = document.getElementById('loginR') as HTMLInputElement;
    const firstName_ = document.getElementById('firstName') as HTMLInputElement;
    const lastName_ = document.getElementById('lastName') as HTMLInputElement;
    const email_ = document.getElementById('email') as HTMLInputElement;
    const passwordR_ = document.getElementById('passwordR') as HTMLInputElement;
    const politics_ = document.getElementById('politics') as HTMLInputElement;
    const infoR_ = document.getElementById('infoR') as HTMLElement;

    if(loginR_.value == ""){ infoR_.textContent = "Введите логин!";  return; }
    if(firstName_.value == "") { infoR_.textContent = "Введите имя!"; return; }
    if(lastName_.value == ""){ infoR_.textContent = "Введите фамилию!";  return; }
    if(email_.value == "") { infoR_.textContent = "Введите адрес элетронной почты!"; return; }
    if(passwordR_.value == "") { infoR_.textContent = "Введите пороль!"; return; }
    if(!politics_.checked) { infoR_.textContent = "Примите соглашение"; return; }

    Api.LogUp(loginR_.value, passwordR_.value).then(response=>{
      if(response.result=='success') {
        AppComponent.IsAuth = true
        disableForms('exampleModalToggle2');
      }
      else infoR_.textContent = "fail!";
    })

    
  }
}


<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Регистрация:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><img src="../assets/auth/login.svg" width="14px" alt=""></span>
            <input type="text" class="form-control" id="loginR" placeholder="Логин" aria-label="Login" aria-describedby="basic-addon1">
          </div>

          <div class="input-group mb-3">
            <input type="text" class="form-control" id="firstName" placeholder="Имя" aria-label="FirstName">
            <span class="input-group-text">/</span>
            <input type="text" class="form-control" id="lastName" placeholder="Фамилия" aria-label="LastName">
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">@</span>
            <input type="text" class="form-control" id="email" placeholder="Почта" aria-label="Email" aria-describedby="basic-addon1">
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><img src="../assets/auth/password.svg" width="14px" alt=""></span>
            <input type="password" class="form-control" id="passwordR" placeholder="Пароль" aria-label="Password" aria-describedby="basic-addon1">
          </div>

          <label for="basic-url" class="form-label">Пол:</label><br>
          <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
            <label class="btn btn-outline-primary" for="btnradio1">Мужской</label>
          
            <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off">
            <label class="btn btn-outline-primary" for="btnradio3">Женский</label>
          </div>
          <br><br>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="politics">
            <label class="form-check-label" for="flexCheckDefault">
              Я принимаю условия <a href="">пользовательского соглашения</a> и <a href="">политики конфиденциальности</a>
            </label>
          </div>
          <strong id="infoR"></strong>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" (click)="register()">Зарегестрироваться</button>
        </div>
      </div>
    </div>
  </div>
<!-- data-bs-toggle="modal" -->

// src/components/register/register.vue
<template>
    <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Регистрация:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><img src="@/assets/auth/login.svg" width="14px" alt=""></span>
            <input type="text" class="form-control" id="loginR" placeholder="Логин" aria-label="Login" aria-describedby="basic-addon1">
          </div>

          <div class="input-group mb-3">
            <input type="text" class="form-control" id="firstName" placeholder="Имя" aria-label="FirstName">
            <span class="input-group-text">/</span>
            <input type="text" class="form-control" id="lastName" placeholder="Фамилия" aria-label="LastName">
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">@</span>
            <input type="text" class="form-control" id="email" placeholder="Почта" aria-label="Email" aria-describedby="basic-addon1">
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><img src="@/assets/auth/password.svg" width="14px" alt=""></span>
            <input type="password" class="form-control" id="passwordR" placeholder="Пароль" aria-label="Password" aria-describedby="basic-addon1">
          </div>

          <label for="basic-url" class="form-label">Пол:</label><br>
          <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
            <label class="btn btn-outline-primary" for="btnradio1">Мужской</label>
          
            <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off">
            <label class="btn btn-outline-primary" for="btnradio3">Женский</label>
          </div>
          <br><br>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="politics">
            <label class="form-check-label" for="flexCheckDefault">
              Я принимаю условия <a href="">пользовательского соглашения</a> и <a href="">политики конфиденциальности</a>
            </label>
          </div>
          <strong id="infoR"></strong>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" @click="logup" data-bs-target="#exampleModalToggle2">Зарегестрироваться</button>
        </div>
      </div>
    </div>
  </div>
</template>
  
  <script>
  import { Api } from '@/coral-api/api';
  import { User } from '@/userdata';
  import { Cookie } from '@/cookie/cookieRW';
  import { disableForms } from '@/DOMserv';

  export default {
    name: "registerComponent",
    methods:{
      logup(){
        const loginR_ = document.getElementById('loginR')
        const firstName_ = document.getElementById('firstName')
        const lastName_ = document.getElementById('lastName')
        const email_ = document.getElementById('email')
        const passwordR_ = document.getElementById('passwordR')
        const politics_ = document.getElementById('politics')
        const infoR_ = document.getElementById('infoR')

        if(loginR_.value == ""){ infoR_.textContent = "Введите логин!";  return; }
        if(firstName_.value == "") { infoR_.textContent = "Введите имя!"; return; }
        if(lastName_.value == ""){ infoR_.textContent = "Введите фамилию!";  return; }
        if(email_.value == "") { infoR_.textContent = "Введите адрес элетронной почты!"; return; }
        if(passwordR_.value == "") { infoR_.textContent = "Введите пороль!"; return; }
        if(!politics_.checked) { infoR_.textContent = "Примите соглашение"; return; }

        Api.LogUp(loginR_.value, passwordR_.value, firstName_.value, lastName_.value).then(response=>{
          if(response.result=='success') {
            User.isAuth = true
            disableForms('exampleModalToggle2');
            Cookie.set('login', loginR_.value)
            Cookie.set('password', passwordR_.value)
            this.$forceUpdate();
          }
          else infoR_.textContent = "fail!";
        })
      }
    },
    components: { 
    }
  }
  </script>
  
  <style src="./register.css"></style>
