// src/app/component/popular-tour/popular-tour.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-popular-tour',
  templateUrl: './popular-tour.component.html',
  styleUrls: ['./popular-tour.component.css']
})
export class PopularTourComponent {

}

<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <a href="#" class="btn btn-primary">Подробнее</a>
    </div>
  </div>

// src/components/popular-tour/popular-tour.vue
<template>
    <div class="card" style="width: 18rem;">
        <img src="" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <a href="#" class="btn btn-primary">Подробнее</a>
    </div>
  </div>
</template>
  
  <script>
  
  export default {
    name: "popularTourComponent",
    components: { 
    }
  }
  </script>
  
  <style src=""></style>
